name: torchseer
favicon: null
layout_spectrum: 0.09992
typography_spectrum: 0.43016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3277599895372987
  lightness: 0.26142140617594123
  saturation: 0.9016313669271767
  rhythmicContrast: 0.4955033438745886
purpose: []
