name: torchseer
favicon: null
layout_spectrum: 0.41096
typography_spectrum: 0.60742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110d0a'
    - '#5f4934'
    - '#837256'
    - '#cfa985'
    - '#eae2cf'
  brandStrength: 0.3277599895372987
  lightness: 0.26142140617594123
  saturation: 0.9016313669271767
  rhythmicContrast: 0.4955033438745886
purpose: []
